### ISSUE TITLE
Проблема с хромом

### ISSUE THREAD

**Issue by Burilmishka** [veks/button-visually-impaired-jquery#9]
Не могу понять почему не работает в Chrome. В мозилле работает. Хром обновил. 
Использую версию на jquery. Просто выкачал ваш шаблон, только свои пути расставил на стили и js. ПишетЖ
ResponsiveVoice r1.5.12
bvi.min.js:4 Button visually impaired v1.0.8
responsivevoice.js:95 RV: Voice support ready ....но это и в мозилле пишет
Тыкните меня носом, если я что-то неправильно сделал.

Также при включении режима слабовидящих эементы с классом "bvi-hide" не скрываются(это в мозилле увидел).

**Comment by veks** [comment]
@Burilmishka, попробуй очистить кеш
